server:
  port: 8051
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guodianwei/spring-cloud-study/
          search-paths: config-repo
          username: dianweichn@gmail.com
          password: GUOdw*21
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/